CREATE TABLE Cars ( 
id INT NOT NULL AUTO_INCREMENT,
VIN VARCHAR(255) NOT NULL,
manufacturer VARCHAR(255) NOT NULL,
model VARCHAR(255) NOT NULL,
year_ int not null,
color VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Customers (
id INT NOT NULL AUTO_INCREMENT,
customerID VARCHAR(255) NOT NULL, 
name_ VARCHAR(255) NOT NULL, 
phone VARCHAR(255) NOT NULL, 
email VARCHAR(255) NOT NULL,
address VARCHAR(255) NOT NULL,  
city VARCHAR(255) NOT NULL, 
state_province VARCHAR(255) NOT NULL,
country VARCHAR(255) NOT NULL, 
zip_postalcode int,
PRIMARY KEY (id)
);

CREATE TABLE Salesperson (
id INT NOT NULL AUTO_INCREMENT,
staffID VARCHAR(255) NOT NULL, 
name_ VARCHAR(255) NOT NULL, 
store VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Invoices (
id INT NOT NULL AUTO_INCREMENT,
invoice_number int,
date_ VARCHAR(255) NOT NULL,
car VARCHAR(255) NOT NULL, 
customer VARCHAR(255) NOT NULL, 
salesperson VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);


